language: ruby
sudo: false
cache: bundler
language: ruby
before_install:
  - mkdir -p "$HOME/bin" && curl -o "$HOME/bin/phantomjs" https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1 && chmod +x "$HOME/bin/phantomjs"
  - export PATH="$HOME/bin:$PATH"
env:
  - SOLIDUS_BRANCH=v2.0 DB=postgres
  - SOLIDUS_BRANCH=v2.1 DB=postgres
  - SOLIDUS_BRANCH=v2.2 DB=postgres
  - SOLIDUS_BRANCH=v2.3 DB=postgres
  - SOLIDUS_BRANCH=v2.4 DB=postgres
  - SOLIDUS_BRANCH=v2.5 DB=postgres
  - SOLIDUS_BRANCH=master DB=postgres
  - SOLIDUS_BRANCH=v2.0 DB=mysql
  - SOLIDUS_BRANCH=v2.1 DB=mysql
  - SOLIDUS_BRANCH=v2.2 DB=mysql
  - SOLIDUS_BRANCH=v2.3 DB=mysql
  - SOLIDUS_BRANCH=v2.4 DB=mysql
  - SOLIDUS_BRANCH=v2.5 DB=mysql
  - SOLIDUS_BRANCH=master DB=mysql
rvm:
  - 2.3.0
